### ISSUE TITLE
ERROR: Failed to run squeezelite.

### ISSUE THREAD

**Issue by philipp90** [christianTF/LoxBerry-Plugin-squeezelite#59] opened 2018-12-02 18:36 UTC
Hi,

first of all - thanks for this plugin!

Unfortunately the frontend isn't showing any output devices anymore.

The log file shows the following error: `ERROR: Failed to run squeezelite.`.

https://github.com/christianTF/LoxBerry-Plugin-squeezelite/blob/9be1471f1a3cec528c613b8537c98a8cecd9de69/webfrontend/cgi/index.cgi#L254

Restarting the raspberry (b+), uninstalling and reinstalling the plugin again (with reboots in between, as described in https://github.com/christianTF/LoxBerry-Plugin-squeezelite/issues/53) nor installing it on a fresh loxberry fixed the issue.
I've also tried to make the `/data/plugins/squeezelite/squeezelite-x64` executable (https://github.com/christianTF/LoxBerry-Plugin-squeezelite/issues/55), but it didn't help either.

Running `squeezelite` via ssh is working fine, btw.

Do you may have any other suggestions?

Regards,
Philipp

**Comment by christianTF** [comment] 2018-12-02 21:34
Hi Philipp,
I‘ll try a fresh install tomorrow. Let me see if I can reproduce the issue.

Christian

**Comment by christianTF** [comment] 2018-12-03 18:07
Hi Philipp,

I'm currently in on a new installation on a Raspberry Pi 1 (yessss, it's slow) and it seems to be a timing issue with permissions, but I'm not 100% sure what the issue is. Finally I could get it to work, but I'm using the dev build.

Could you please try:
- Enable alternative binaries
- Reboot
- Go to the plugin page and see if it could list the players
- If not, wait two minutes and refresh, and possibly again....
- If you still see no devices:
- Use putty to logon to shell

In my installation, it did not show up the outputs as in yours.
I refreshed several times and nothing happened.
Then, and I don't know if this was a happy coincidence or some kind of "user profile bug", I logged on as loxberry with putty, and a second later the refresh showed up the outputs.

May you retry this again.
I am in the dev branch where I already changed/updated some things to LB1.x during installation, so if your re-check does not work, I instruct you how you can install the dev branch.

Regards, Christian

**Comment by philipp90** [comment] 2018-12-29 14:25
Hi Christian,

thank you for your fast reply and I'm very sorry for my late response.

I've already tried all the steps before. Nevertheless I've tried it again but it doesn't work for me.
Unfortunately the dev branch also didn't work.

I did some debugging and at least I've fixed the error message and the devices are showing up now.
What I've changed: I simply removed the `sudo` keyword from this command.
https://github.com/christianTF/LoxBerry-Plugin-squeezelite/blob/9be1471f1a3cec528c613b8537c98a8cecd9de69/webfrontend/cgi/index.cgi#L254

Then I've added 5 Instances but the frontend showed `Aktuell laufen 2 Squeezelite Prozesse.` instead of 5. Tough there was only one running instance in LMS. After a reboot there were no more running instances left.

Thus my machine isn't able to start any instances as well. I did some further debugging and was able to to properly run the plugin for my need.

Here's what I've done:
https://github.com/philipp90/LoxBerry-Plugin-squeezelite/commit/4eea425e42a4f455846bbcebeeb747700d3cd8b5
https://github.com/philipp90/LoxBerry-Plugin-squeezelite/commit/9313842270cc53f129eac2db40add1b61d193c22

Regards, Philipp

**Comment by christianTF** [comment] 2018-12-29 15:29
Hi Philipp,

Not using sudo will drop support for LoxBerry 0.2.3.

There is a file in Config/plugins/squeezelite called sudoers.v*
Deleting this file will redo the sudo permissions.

In fact, something is strange in the install process since LB1.x (I also had that the squeezelox user wasn’t created).

In the nearer future, I will completely rewrite the install procedure, as LB1.x has issues fixed, that the old install had to handle itself.

If some instances do no come up, it might be because of the ALSA output. Some are not working as all.

**Comment by philipp90** [comment] 2019-01-13 18:38
Hi Christian,

I didn't find any file called `sudoers.v*`:
```
$ ls -la /opt/loxberry/config/plugins/squeezelite/
total 20
drwxr-xr-x 2 loxberry loxberry 4096 Dec 29 15:36 .
drwxr-xr-x 8 loxberry loxberry 4096 Jan  6 14:18 ..
-rw-r--r-- 1 loxberry loxberry 2548 Dec 29 15:33 example.cfg
-rw-r--r-- 1 loxberry loxberry    9 Dec 29 15:33 is_raspbian.info
-rwxr--r-- 1 loxberry loxberry  990 Jan 10 19:30 plugin_squeezelite.cfg
```

I've also searched through the whole `/opt/loxberry/**/*` folder without any result:
```
$ find /opt/loxberry/ -type f -name sudo*
```

I will try it again, if there's a new release. In the meantime I use my patched version.

Thanks for your support!

Everything else is working fine btw, e.g. the communication with the "miniserver" - I really love the whole loxberry project! Many thanks to you and all the other contributors!

**Comment by christianTF** [comment] 2019-05-08 22:18
Currently working on Squeezelite Player Plugin V1.0.x for LoxBerry 1.4.1 (and above).
The installation and permission issues are already fixed.

I will close the issue for now.
Follow the "Releases" here on GitHub, or the LoxForum Thread, for an announcement of the Pre-Release.

Christian

**Closed as completed by christianTF** 2019-05-08 22:18 UTC
Labels: Major bug
